### ISSUE TITLE
How fast?

### ISSUE THREAD

**Issue by PanayotCankov** [css/gonzales#16]
I am running performance tests and I am looking for fast CSS parser that can run on mobile device in decent times.

You should be able to clone https://github.com/NativeScript/NativeScript/tree/implement-css-parser and `npm I` `npm run unit-test` to run the mocha tests with some perf tests on parsers, the numbers on my mac mini are:
```
Parsers perf: rework: 21.180111ms. shady: 14.489263ms. parse-css: 19.737071ms. gonzalesDuration: 84.449088 nativescript-parse: 6.366284999999948ms.
```
Am I doing something wrong? The rework is rather slow but still gets better numbers than your parser. Don't bother with {N}'s time, the parser is incomplete it will get slower.

**Comment by lahmatiy** [comment]
Gonzales is outdated and doesn't maintained for years (since 2013). If you interesting in gonzales, take a look for [gonzales-pe](https://github.com/tonyganch/gonzales-pe), this is a fork of gonzales with post processors support (sass, less) and other improvements, that maintains at the moment.

If you are looking for the fastest parser, then there are other alternatives. See 
[the CSS parsers benchmark](https://github.com/postcss/benchmark#parsers) by PostCSS team to choose your favourite one.

**Comment by lahmatiy** [comment]
I've added deprecation notes on top of readme. Hope it helps to find an answers.
